### ISSUE TITLE
TypeError when using resnet18 for classification

### ISSUE THREAD

**Issue by Purin100** [ServiceNow/geo-bench-experiments#5]
I generated a classification task following the instruction on the page. Everything was fine at this stage.

When I tried to run the experiment with m-eurosat dataset, I saw the following error message:
![Problem](https://github.com/ServiceNow/geo-bench-experiments/assets/97730715/d9e57ab6-c396-4462-a3dc-50b971368b96)
The pytorch version of my computer is torch 2.3.0 with CUDA 11.8, python version is 3.10.14.

I tried convnext model on the same dataset, this error didn't show up.

It would be appreciated that you can fix this problem. Thank you!

By the way, I find another error when using resnet50 model. It seems that pytorch no longer accepting _monument_ which exists in the resnet50.yaml as a parameter for Adam optimizer. Keeping the parameter will cause an error when running the experiment. I modified optimizer part in resnet50.yaml (on my computer) according to that in resnet18.yaml, and this error got fixed.

Could you please update resnet50.yaml in your project to fix this error? Thank you!

**Comment by nilsleh** [comment]
Hi @Purin100 , thanks for the issue. The error you are seeing occured, because the `torchgeo` dependency changed the return statement of the [function](https://github.com/microsoft/torchgeo/blob/91bbb83bf93b2ec168e502466ca4ab7e2fe28a87/torchgeo/trainers/utils.py#L74) we used. I just pushed to main, and should be fixed now. I can run classification experiments.

**Comment by Purin100** [comment]
Hello @nilsleh, I tested the code on my computer and it worked well. Thank you!
